package org.instnt.accept.instntsdk.enums;

public enum CallbackType {
    SUCCESS_INIT_TRANSACTION,
    SUCCESS_IMAGE_UPLOAD,
    SUCCESS_FORM_SUBMIT,
    SUCCESS_SEND_OTP,
    SUCCESS_VERIFY_OTP,
    SUCCESS_DOC_SCAN,

    ERROR_INIT_TRANSACTION,
    ERROR_FORM_SUBMIT,
    ERROR_SEND_OTP,
    ERROR_VERIFY_OTP,
    ERROR_DOC_SCAN_CANCELLED,
    ERROR_DOC_SCAN_NOT_CAPTURED,
}
